# Generated by Django 4.2.2 on 2023-07-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RealEstateListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bhk", models.IntegerField()),
                ("bath", models.FloatField()),
                ("total_sqft", models.FloatField()),
                ("price", models.FloatField()),
            ],
        ),
    ]
